root: true
extends: airbnb-base
env:
  es6: true
  node: true
  jest: true
rules:
  indent: [error, 2, { SwitchCase: 1 }]
  max-len: [
    error, {
      code: 80,
      ignoreComments: true
    }]
  no-trailing-spaces: error
  no-mixed-operators: off
  no-underscore-dangle: off
  operator-linebreak: off
