root: true
extends: airbnb-base
env:
  es6: true
  node: true
rules:
  indent: [error, 2, { SwitchCase: 1 }]
  max-len: [
    error, {
      code: 80,
      ignoreComments: true,
      IgnoredPatterns:
        - '^class'
        - '^module.exports'
    }]
  no-trailing-spaces: error
